version: "3.9"

services:
  auctoritas-be:
    container_name: auctoritas-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - praetor-net

networks:
  praetor-net:
    driver: bridge
