package it.aredegalli.auctoritas.enums;

public enum AuditEventTypeEnum {
    APPLICATION_GET,
    APPLICATION_CREATE,
    APPLICATION_UPDATE,
    APPLICATION_DISABLE,
    APPLICATION_ENABLE,

    ROLE_GET,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    PERMISSION_GET,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,

    PERMISSION_ROLE_GET,
    PERMISSION_ROLE_CREATE,
    PERMISSION_ROLE_DELETE,

    USER_ROLE_GET,
    USER_ROLE_CREATE,
    USER_ROLE_DELETE,

    APPLICATION_ROLE_GET,
    APPLICATION_ROLE_CREATE,
    APPLICATION_ROLE_DELETE,
}
